### PR TITLE
Add national roads to dumps and explore tiles

### PR DESCRIPTION
**Pull request by mileswwatkins**
closes https://github.com/orma/openroads-vn-analytics/issues/185

### CODE REVIEW

**Comment by mileswwatkins** [comment]
@geohacker, I've run these scripts locally as one-offs, but haven't gotten to run the full Docker system yet. The best way to merge this in may be to:

1. Give my code changes a read-through
2. Deploy it (instructions in the README), and see if the workers run successfully. You can check this by looking at the outputs (ie, do the production tiles now have national highways on them; that is, do the national tiles now span the whole country? And do the province dumps now contain national roads?). @matthewhanson can point you to how to access the production worker logs, to look for errors.

Note that this repo takes a long time (~35 mins) to build, so no rush :)

**Comment by mileswwatkins** [comment]
Let me know if you bump into anything that I've screwed up!

**Comment by geohacker** [comment]
Thank you @mileswwatkins! Things look good to me on a glance - going to deploy and see what happens.

**Comment by geohacker** [comment]
> ie, do the production tiles now have national highways on them; that is, do the national tiles now span the whole country? And do the province dumps now contain national roads?

I probably need some help to figure out what the right tilesets are here. @olafveerman would you know? Are we talking about `conflated.mbtiles` or `openroads-vn-tiles-prod/tiles/`?

cc @mileswwatkins

**Comment by mileswwatkins** [comment]
You’d be looking at the vector tiles on Mapbox, that power the Explore view.

**Comment by geohacker** [comment]
@mileswwatkins thank you for the quick response! this?

image

That doesn't look like it got updated.

**Comment by geohacker** [comment]
image

looks like it's processing now.

**Comment by mileswwatkins** [comment]
Yup, keep me posted. I don't have creds to view the MB tilesets or the logs. However, 13 days seems very stale to me!

**Comment by geohacker** [comment]
Umm it's still processing - and looks like this isn't a new run because the last modified date is 14 days. I'm going to dig through the tileset to see if all is well. Will pull it down locally and inspect.

**Comment by geohacker** [comment]
image

The mbtiles look fine locally. I'm uploading manually on mapbox to see what happens but something is off.

**Comment by geohacker** [comment]
Hah interesting - the manual upload from the browser worked just fine.

**Comment by geohacker** [comment]
* the conflation script was taking more about 33 mins to finish
* per @mileswwatkins's recommendation [I changed the order of how merging national roads](https://github.com/orma/openroads-vn-tiler/pull/38/commits/a682e42ae311ada4cbcf3d550ef832c68d8477d4).
* the cron was set to run every 5 mins. bumped this up to run every 30. 
* only a deploy is pending, but we're all set here.

**Pull request merged**
